# Generated by Django 6.0.3 on 2026-05-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
